# Sample config file (DO NOT PUT REAL VALUES)

TRADE_MODE = "PAPER"  # or LIVE

ANGEL_API_KEY = ""
ANGEL_CLIENT_ID = ""
ANGEL_MPIN = ""
ANGEL_TOTP_SECRET = ""

TELEGRAM_BOT_TOKEN = ""
TELEGRAM_CHAT_ID = ""
